name: xmonad-quark

dependencies:
    - base
    - fitspec
    - split
    - text
    - xmonad
    - xmonad-contrib

library:
    source-dirs: src

executables:
    xmonad:
        source-dirs:  app
        main:         Main.hs
        dependencies: xmonad-quark
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
