* My XMonad Configuration

XMonad is a library for creating a tiling window manager in Haskell, a programming language with particular appeal to me as a mathematician. Proponents of tiling window managers often praise their minimalism. While appreciating how fast they run, I have also put effort into keeping around some eyecandy!

** Installation

The installation instructions for this config currently live at [[/../../README.md][the root README file]] for this repository. It depends on certain scripts in https://github.con/quarkQuark/dotfiles/tree/master/.scripts as well as the following.
- Required dependencies ::
  #+begin_src sh
    alacritty
    aur/deadd-notification-center  # Alternatively use `dunst`
    bc
    brightnessctl
    nitrogen
    aur/notify-send-py
    redshift
    rofi
    spectacle
  #+end_src
- Semi-optional dependencies :: Not necessary for core functionality, but necessary for certain keybindings to do anything
  #+begin_src sh
    emacs
    pcmanfm
    qutebrowser
    ranger
    vivaldi
    zathura
  #+end_src
- Optional dependencies :: These programs are preferred for some functionality, but have fallbacks
  #+begin_src sh
    tmux  # Automatically runs in terminal scratchpad
  #+end_src

** Keybindings

One of the most unique features of this config is the keybinding cheatsheet that can be brought up at any time with =Super+?=, inspired by AwesomeWM. This is achieved with [[https://www.stackage.org/haddock/lts-18.5/xmonad-contrib-0.16/XMonad-Util-NamedActions.html][XMonad.Util.NamedActions]] and displayed using =dzen2= and [[/.scripts/dzen2-display-cheatsheet][a shell script with lots of regex]].

In [[./src/modifiers.sh][src/modifiers.sh]] I also bind =Caps Lock= to =Hyper= and =Space=, when held down, to an additional =Super= (Windows) key. The goal of this is to enable more ergonomic keybindings. Eventually I will include a list of keybindings in this README, but until then refer to the screenshot at the top of this page.

** Panels

I've configured XMonad to work with three different panels. The current panel can be easily changed by changing the =myBar= variable in [[/app/Main.hs][app/Main.hs]].

- Tint2 ::

  This is the most bloated and least well integrated with XMonad, but it allows me to have a vertical panel.

- XMobar ::

  The standard XMonad status bar. Very simple and lightweight, and extremely well integrated with XMonad itself. This is the least buggy, but also the least pretty.

- Taffybar ::

  Like XMobar, but with more eyecandy.
