* My XMonad Configuration

XMonad is a library for creating a tiling window manager in Haskell, a programming language with particular appeal to me as a mathematician. Proponents of tiling window managers often praise their minimalism. While appreciating how fast they run, I have also put effort into keeping around some eyecandy!

** Installation

*** Dependencies

- Required :: =kitty nitrogen redshift rofi spectacle network-manager network-manager-applet pasystray udiskie xcape xorg-xmodmap xorg-xrandr aur/deadd-notification-center aur/notify-send-py aur/stack-static aur/picom-ibhagwan-git=
- Scripts :: https://github.com/quarkQuark/scripts
- To use XMobar :: =stalonetray xfce4-power-manager=
- To use Taffybar :: =lxqt-power-management= and run =stack install status-notifier-item=
- Not necessary for core functionality :: =dzen2 emacs pcmanfm qutebrowser ranger tmux vivaldi zathura=

*** Install XMonad

1. Clone this config as well as my forks of the =xmonad= and =xmonad-contrib= source code.

   #+begin_src sh
     git clone git@github.com:quarkQuark/xmonad-quark $HOME/Projects/xmonad-quark
     git clone git@github.com:quarkQuark/xmonad $HOME/Projects/xmonad-quark
     git clone git@github.com:quarkQuark/xmonad-contrib $HOME/Projects/xmonad-quark
   #+end_src

   To link my forks with the official repositories, run:

   #+begin_src sh

     cd $HOME/Projects/xmonad
     git remote add upstream git@github.com:xmonad/xmonad

     cd $HOME/Projects/xmonad-contrib
     git remote add upstream git@github.com:xmonad/xmonad-contrib

   #+end_src

2. Build and install using stack (I install stack using ghcup).

   #+begin_src sh

     ./$HOME/Projects/xmonad-quark/build
     stack install xmobar

   #+end_src

3. Enable access from login managers by creating the following file in =/usr/share/xsessions/xmonad.desktop=:

#+begin_example conf
  [Desktop Entry]
  Encoding=UTF-8
  Type=Application
  Name=XMonad
  Comment=Lightweight X11 tiling window manager written in Haskell
  Exec=xmonad
  Icon=xmonad
  Terminal=false
  StartupNotify=false
  Categories=Application
#+end_example
