* My XMonad Configuration

XMonad is a library for creating a tiling window manager in Haskell, a programming language with particular appeal to me as a mathematician. Proponents of tiling window managers often praise their minimalism. While appreciating how fast they run, I have also put effort into keeping around some eyecandy!

** Installation

*** Dependencies

- Required :: =alacritty bc brightnessctl nitrogen redshift rofi spectacle network-manager network-manager-applet pasystray udiskie xcape xorg-xmodmap xorg-xrandr aur/deadd-notification-center aur/notify-send-py aur/stack-static aur/picom-ibhagwan-git=

- Scripts from https://github.com/quarkQuark/scripts ::

#+begin_src sh
  git clone git@github.com:quarkQuark/scripts $HOME/.scripts/repo
  cp $HOME/Projects/xmonad-quark/scripts/* $HOME/.scripts
#+end_src

- For XMobar :: =stalonetray xfce4-power-manager=
- For Taffybar :: =lxqt-power-management=
- Not necessary for core functionality :: =dzen2 emacs pcmanfm qutebrowser ranger vivaldi zathura=

- Optional :: These programs are preferred for some functionality, but have fallbacks
  #+begin_src sh
    tmux  # Automatically runs in terminal scratchpad
  #+end_src

*** Install XMonad

#+begin_src sh
  git clone git@github.com:quarkQuark/xmonad-quark $HOME/Projects/xmonad-quark
  cd $HOME/Projects/xmonad-quark && stack install
  cd $HOME/.config/taffybar && stack install
  stack install xmobar
  stack install status-notifier-item  # For taffybar's system tray
#+end_src

Then create the file =/usr/share/xsessions/xmonad.desktop= with the following contents:

#+begin_example conf
  [Desktop Entry]
  Encoding=UTF-8
  Type=Application
  Name=XMonad
  Comment=Lightweight X11 tiling window manager written in Haskell
  Exec=xmonad
  Icon=xmonad
  Terminal=false
  StartupNotify=false
  Categories=Application
#+end_example

** Keybindings

One of the most unique features of this config is the keybinding cheatsheet that can be brought up at any time with =Super+?=, inspired by AwesomeWM. This is achieved with [[https://www.stackage.org/haddock/lts-18.5/xmonad-contrib-0.16/XMonad-Util-NamedActions.html][XMonad.Util.NamedActions]] and displayed using =dzen2= and [[/.scripts/dzen2-display-cheatsheet][a shell script with lots of regex]].

In [[./src/modifiers.sh][src/modifiers.sh]] I also bind =Caps Lock= to =Hyper= and =Space=, when held down, to an additional =Super= (Windows) key. The goal of this is to enable more ergonomic keybindings. Eventually I will include a list of keybindings in this README, but until then refer to the screenshot at the top of this page.

** Panels

I've configured XMonad to work with three different panels. The current panel can be easily changed by changing the =myBar= variable in [[/app/Main.hs][app/Main.hs]].

- Tint2 ::

  This is the most bloated and least well integrated with XMonad, but it allows me to have a vertical panel.

- XMobar ::

  The standard XMonad status bar. Very simple and lightweight, and extremely well integrated with XMonad itself. This is the least buggy, but also the least pretty.

- Taffybar ::

  Like XMobar, but with more eyecandy.
