#!/bin/sh

# Set correct cursor
xsetroot -cursor_name left_ptr

# On which side of the primary display is the laptop?
side="${1:-r}"

# Keyboard

# Alt Gr sends 'mod1' (same as Alt)
#xmodmap -e 'remove mod5 = ISO_Level3_Shift'
#xmodmap -e 'add mod1 = ISO_Level3_Shift'
setxkbmap -option lv3:ralt_alt

# Caps Lock sends 'mod3'
setxkbmap -option caps:hyper       # The caps key is now seen by the system as Hyper
xmodmap -e 'remove mod4 = Hyper_L' # Hyper used to do the same as Super
xmodmap -e 'add mod3 = Hyper_L'    # But now Hyper does its own thing!
# Hyper (Caps Lock) on release sends C-esc
pkill xcape # Avoid typing multiple spaces on one keypress
xcape -e 'Hyper_L=Control_L|Escape'

# S on release sends C-M-S-F1
#xcape -e 'Shift_L=Super_L|Control_L|Alt_L|Shift_L|F1'
#xcape -e 'Shift_R=Super_R|Control_R|Alt_R|Shift_R|F1'

# Holding Space (keycode 65) sends Super
xmodmap -e "keycode 65 = Super_L" # Space (65) generates Super
# Map space to an unused keycode to keep it accessible to xcape
xmodmap -e "keycode any = space"
# Tapping space works properly
xcape -e "Super_L=space" # Space works normally when tapped

# Dell XPS 9310 2-in-1
# Laptop: eDP-1
# Right USBc -> Dock HDMI-1: DP-1-1
# Right USBc -> Dock HDMI-2: DP-1-2
# Left  USBc -> Dock HDMI-1: DP-3-1
# Left  USBc -> Dock HDMI-2: DP-3-2

# Different names on different laptops
screen0="eDP-1"
screen1="DP-1-1"
ratio="1920x1200"
w=1920
h=1200
wSmall=960
hSmall=600

# If no eDP-1, assume this is my old laptop
xrandr | grep -q "eDP-1" \
    || screen0="eDP1" \
    || screen1="HDMI1" \
    || h=1080 \
    || hSmall=540

ratio="${w}x${h}"
ratiosmall="${wSmall}x${hSmall}"

[ $side = "0" ] \
    && xrandr \
        --output $screen0 --primary \
          --mode $ratio --scale 1x1 \
    && nitrogen --restore && xmonad --restart \
    && exit


# Monitor setup

offset=$hSmall
pos0=""
pos1=""

case $side in
    l)  pos1=${w}x0
        pos0=0x${offset}
        ;;
    r)  pos1=${w}x0
        pos0=3840x${offset}
        ;;
    *)  pos1=${w}x0
        pos0=3840x${offset}
        ;;
esac

# Monitor on right
xrandr \
    --output $screen1 --primary \
      --mode 1920x1080 --pos $pos1 \
    --output $screen0 \
      --mode $ratio --pos $pos0 --scale 1x1 \
    && nitrogen --restore && xmonad --restart
#xrandr \
#    --output HDMI1 --primary \
#      --mode 1920x1080 --pos 1920x0 \
#    --output eDP1 \
#      --mode 1920x1080 --pos $pos \
#    && nitrogen --restore && xmonad --restart
